import { Stage } from './Stage';
import { Ticker } from '../system/Ticker';
import { Matrix } from '../geom/Matrix';
import { Vector } from '../geom/Vector';
import { Rectangle } from '../geom/Rectangle';
import { TouchEvent } from '../event/TouchEvent';
import { EventEmitter } from '../event/EventEmitter';
export declare class Layer extends EventEmitter {
    static pixelRatio: number;
    name: string;
    tag: string;
    touchable: boolean;
    protected $x: number;
    protected $y: number;
    protected $width: number;
    protected $height: number;
    protected $anchorX: number;
    protected $anchorY: number;
    protected $skewX: number;
    protected $skewY: number;
    protected $scaleX: number;
    protected $scaleY: number;
    protected $rotation: number;
    protected $alpha: number;
    protected $visible: boolean;
    protected $smoothing: boolean;
    protected $background: string;
    protected $dirty: boolean;
    protected $stage: Stage;
    protected $parent: Layer;
    protected $children: Array<Layer>;
    protected $shouldEmitTap: boolean;
    protected $touches: Array<boolean>;
    protected readonly $canvas: HTMLCanvasElement;
    protected readonly $context: CanvasRenderingContext2D;
    constructor();
    x: number;
    y: number;
    width: number;
    height: number;
    anchorX: number;
    anchorY: number;
    skewX: number;
    skewY: number;
    scaleX: number;
    scaleY: number;
    rotation: number;
    alpha: number;
    visible: boolean;
    smoothing: boolean;
    background: string;
    readonly dirty: boolean;
    readonly stage: Stage;
    readonly parent: Layer;
    readonly children: Array<Layer>;
    readonly ticker: Ticker;
    readonly canvas: HTMLCanvasElement;
    resize(width: number, height: number): this;
    addChild(child: Layer): this;
    addChildAt(child: Layer, index: number): this;
    replaceChild(oldChild: Layer, newChild: Layer): this;
    getChildByName(name: string): Layer;
    getChildrenByTag(tag: string): Array<Layer>;
    getChildAt(index: number): Layer;
    getChildIndex(child: Layer): number;
    hasChild(child: Layer): boolean;
    swapChildren(child1: Layer, child2: Layer): this;
    swapChildrenAt(index1: number, index2: number): this;
    setChildIndex(child: Layer, index: number): this;
    removeChild(child: Layer): this;
    removeChildAt(index: number): this;
    removeChildByName(name: string): this;
    removeChildrenByTag(tag: string): this;
    removeAllChildren(): this;
    removeSelf(): this;
    protected $markDirty(sizeDirty?: boolean): void;
    protected $markParentDirty(): void;
    protected $resizeCanvas(): void;
    protected $resizeParentCanvas(): void;
    protected $getTransform(): Matrix;
    protected $getChildTransform(child: Layer): Matrix;
    protected $getChildBounds(child: Layer): Rectangle;
    protected $getContentBounds(): Rectangle;
    protected $emitTouchEvent(event: TouchEvent, inside: boolean): boolean;
    protected $emitAdded(parent: Layer): void;
    protected $emitRemoved(): void;
    protected $emitAddedToStage(stage: Stage): void;
    protected $emitRemovedFromStage(): void;
    protected $localHitTest(vector: Vector): boolean;
    protected $isChildVisible(child: Layer): boolean;
    protected $drawChild(child: Layer): number;
    protected $render(): number;
    on(type: string, listener: (...args: any[]) => void): this;
    off(type: string, listener?: (...args: any[]) => void): this;
}
