import Layer, { BackgroundFillMode } from './Layer';
import Image from '../media/Image';
import Ticker from '../core/Ticker';
import Rectangle from '../geom/Rectangle';
import Event from '../event/Event';
import ResourceManager, { ResourceInfo, ResourceManagerOption } from '../net/ResourceManager';
export default class Stage extends Layer {
    static readonly NO_SCALE: string;
    static readonly NO_BORDER: string;
    static readonly SHOW_ALL: string;
    static readonly EXACT_FIT: string;
    static readonly FIXED_WIDE: string;
    static readonly FIXED_NARROW: string;
    static readonly FIXED_WIDTH: string;
    static readonly FIXED_HEIGHT: string;
    protected $drawCalls: number;
    protected $scaleMode: string;
    protected $viewportWidth: number;
    protected $viewportHeight: number;
    protected $renderBounds: Rectangle;
    protected $viewportBackgroundColor: string;
    protected $viewportBackgroundImage: Image;
    protected $viewportBackgroundPattern: CanvasPattern;
    protected $viewportBackgroundFillMode: BackgroundFillMode;
    protected readonly $ticker: Ticker;
    protected readonly $viewportCanvas: HTMLCanvasElement;
    protected readonly $viewportContext: CanvasRenderingContext2D;
    protected readonly $boundResizeViewportCanvas: () => void;
    constructor(canvas?: HTMLCanvasElement);
    protected $initEvents(): void;
    x: number;
    y: number;
    scaleMode: string;
    viewportWidth: number;
    viewportHeight: number;
    viewportBackgroundColor: string;
    viewportBackgroundImage: Image;
    viewportBackgroundFillMode: BackgroundFillMode;
    readonly drawCalls: number;
    readonly fps: number;
    readonly ticker: Ticker;
    createResourceManager(list: Array<ResourceInfo>, options?: ResourceManagerOption): ResourceManager;
    protected $addTouchEventListeners(): void;
    protected $dispatchTouches(type: string, event: Event): void;
    protected $dispatchTouchEvent(type: string, touch: Touch | MouseEvent): void;
    protected $calculateRenderBounds(): void;
    protected $resizeCanvas(): void;
    protected $resizeViewportCanvas(): void;
    protected $render(): number;
}
